CREATE TABLE ea_employee (
  id SERIAL PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  lastname VARCHAR(250) NOT NULL,
  email VARCHAR(250) UNIQUE NOT NULL,
  description VARCHAR(250)
);

CREATE TABLE passwords (
  id SERIAL PRIMARY KEY,
  email VARCHAR(250) UNIQUE NOT NULL,
  password VARCHAR(500) NOT NULL
);
